### ISSUE TITLE
Glad to found this

### ISSUE THREAD

**Issue by shtefcs** [rclai/meteor-x-ray#1]
Hi Richard,

I am glad I found this, it's something i was looking for. I would like to build scraping/automating app using X-ray, meteorjs, nightmare. I wanted to ask do u provide freelancing ? We can do Odesk contract if you are interested.

Let me know on skype:ksifoking or email:shtefistefi@yahoo.co.uk

**Comment by rclai** [comment]
Thanks for reaching out, but I am unavailable for freelance.
