### ISSUE TITLE
Documentation for Select?

### ISSUE THREAD

**Issue by shwaydogg** [rclai/meteor-x-ray#2]
Where does the `select` method come from in your example?  It works and there is obvious relation to the x-ray but I don't see it in the x-ray or cheerio docs. 

```
xray('http://google.com')
  .select('title')
  .run(function (err, title) {
```

I see that your essentially just including the NPM package so i'm unclear why there is a difference in syntax.  

Essentially I'm looking for a mapping for _how_ to use the x-ray documentation here.

**Comment by rclai** [comment]
Don't use this package anymore. Use `meteorhacks:npm` to include the official NPM of the x-ray library.

**Comment by rclai** [comment]
My docs are old.

**Comment by vedovato** [comment]
Sorry for reviving this issue @rclai but how did u make it return synchronously?

**Comment by rclai** [comment]
It's right in the [usage example](https://github.com/rclai/meteor-x-ray#usage). Obviously, the xray code is out of date, so adapt the code to the right usage.

And also note that my package is no longer maintained.

**Comment by vedovato** [comment]
Ya, just read more on fibers after posting here. Thank you, @rclai.
